version: '3.8'
services: 
  "web-app":
    build: "./web-application"
    ports:
      - "3000:8080"
    volumes:
      - "./web-application/src:/web-application/src"
    depends_on:
      - database
  "database":
    build: "./db"
    environment:
      MYSQL_ROOT_PASSWORD: "abc123"
      MYSQL_DATABASE: "my-platform"
    ports:
      - "3306:3306"
  "redis":
    build: "./redis"
    ports:
    - "6379:6379"

  

